parameters:
#    sahadina_geo.example.class: Sahadina\GeoBundle\Example

services:
#    sahadina_geo.example:
#        class: %sahadina_geo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
