sonata_media:
    class:
        media:   Application\Sonata\MediaBundle\Entity\Media
        #gallery: Application\Sonata\MediaBundle\Entity\Gallery
        #gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm 
    contexts:
        default: 
            providers:
                #- sonata.media.provider.dailymotion
                #- sonata.media.provider.youtube
                - sonata.media.provider.image
                #- sonata.media.provider.file

            formats:
               big:      { width: 500 ,height: 500, quality: 100}
               medium:   { width: 300 ,height: 300, quality: 100}
               small:    { width: 180 ,height: 180, quality: 100}
        restaurant:
            providers:
                - sonata.media.provider.image

            formats:
                big:    { width: 500 , quality: 100}
                medium: { width: 300 ,height: 300, quality: 100}
                small:  { width: 180 ,height: 180, quality: 100}

    cdn:
        server:
            path: /uploads/media 

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
    providers:
        image:
            resizer:    sonata.media.resizer.square
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
doctrine:
    orm:
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                    