<?php
/**
 * 
 * @author achraf
 * @since 27 Mai 2014
 * @copyright Sahadina
 */
namespace Sahadina\GeoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	/**
	 * Returns all available cities 
	 * 
	 */
	public function getCities(){
		
		$em=$this->getEntityManager();
		
		$query = $em->createQuery('
            SELECT c,t
            FROM SahadinaGeoBundle:City c JOIN c.translations t
            ORDER BY t.name DESC
        ');
		
		return $query->getArrayResult();
	}
}
