parameters:
#    sahadina_restaurant.example.class: Sahadina\RestaurantBundle\Example

services:
#    sahadina_restaurant.example:
#        class: %sahadina_restaurant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
