parameters:
#    sahadina_user.example.class: Sahadina\UserBundle\Example

services:
#    sahadina_user.example:
#        class: %sahadina_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
